spring:
  application:
    name: email-server
  redis:
    host: 47.99.196.17
    port: 6379
    jedis:
      pool:
        max-active: 20

server:
  port: 7762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
